// Generic 
export const CHANGE_DIE_TYPE = 'CHANGE_DIE_TYPE';
export const CHANGE_DIE_NUMBER = 'CHANGE_DIE_NUMBER';
export const UPDATE_KEY = 'UPDATE_KEY';


// Powers
export const LOAD_EXISTING_POWERS = 'LOAD_EXISTING_POWERS';
export const ADD_TO_POWERS = 'ADD_TO_POWERS';
export const RESET_CURRENT_POWER = 'RESET_CURRENT_POWER';
export const CHANGE_CURRENT_POWER = 'CHANGE_CURRENT_POWER';
export const CHANGE_DIE_MODIFIER = 'CHANGE_DIE_MODIFIER';
export const UPDATE_ATTACK = 'UPDATE_ATTACK';

// Weapons
export const LOAD_AVAILABLE_WEAPONS = 'LOAD_AVAILABLE_WEAPONS';
export const EDIT_AVAILABLE_WEAPONS = 'EDIT_AVAILABLE_WEAPONS';
export const CHANGE_WEAPON = 'CHANGE_WEAPON';
export const UPDATE_RANGE = 'UPDATE_RANGE';

// Dungeons
export const LOAD_DUNGEONS = 'LOAD_DUNGEONS';
export const UPDATE_EXISTING_DUNGEON = 'UPDATE_EXISTING_DUNGEON';
export const SET_DUNGEON = 'SET_DUNGEON';
export const UPDATE_DUNGEON_KEY = 'UPDATE_DUNGEON_KEY';
export const SET_SLOT_ENTITY = 'SET_SLOT_ENTITY';
export const ADD_TILE = 'ADD_TILE';
export const DUPLICATE_DUNGEON = 'DUPLICATE_DUNGEON';

// Entities

export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const LOAD_MONSTERS = 'LOAD_MONSTERS';
export const UPDATE_EXISTING_ENTITY = 'UPDATE_EXISTING_ENTITY';
export const UPDATE_ENTITY_KEY = 'UPDATE_ENTITY_KEY';
export const UPDATE_POINTS_KEY = 'UPDATE_POINTS_KEY';
export const UPDATE_MOUSEOVER = 'UPDATE_MOUSEOVER';