// Powers
export const LOAD_EXISTING_POWERS = 'LOAD_EXISTING_POWERS';
export const ADD_TO_POWERS = 'ADD_TO_POWERS';
export const RESET_CURRENT_POWER = 'RESET_CURRENT_POWER';
export const CHANGE_CURRENT_POWER = 'CHANGE_CURRENT_POWER';
export const CHANGE_DIE_TYPE = 'CHANGE_DIE_TYPE';
export const CHANGE_DIE_NUMBER = 'CHANGE_DIE_NUMBER';
export const CHANGE_DIE_MODIFIER = 'CHANGE_DIE_MODIFIER';
export const UPDATE_KEY = 'UPDATE_KEY';
export const UPDATE_ATTACK = 'UPDATE_ATTACK';

