export var Weapons = [
	{ category: "Simple",  type: "melee", name: "Club", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Dagger", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Javelin", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Mace", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Sickle", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Spear", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Greatclub", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Morningstar", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Quarterstaff", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "melee", name: "Scythe", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Battleaxe", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Flail", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Handaxe", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Longsword", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Scimitar", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Short sword", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Throwing hammer", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Warhammer", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "War pick", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Falchion", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Glaive", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Greataxe", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Greatsword", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Halberd", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Heavy flail", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Longspear", range: { low: 0, high: 0 },
	{ category: "Military",  type: "melee", name: "Maul", range: { low: 0, high: 0 },
	{ category: "Superior",  type: "melee", name: "Bastard sword", range: { low: 0, high: 0 },
	{ category: "Superior",  type: "melee", name: "Katar", range: { low: 0, high: 0 },
	{ category: "Superior",  type: "melee", name: "Rapier", range: { low: 0, high: 0 },
	{ category: "Superior",  type: "melee", name: "Spiked chain", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "ranged", name: "Hand crossbow", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "ranged", name: "Sling", range: { low: 0, high: 0 },
	{ category: "Simple",  type: "ranged", name: "Crossbow", range: { low: 0, high: 0 },
	{ category: "Military",  type: "ranged", name: "Longbow", range: { low: 0, high: 0 },
	{ category: "Military",  type: "ranged", name: "Shortbow", range: { low: 0, high: 0 },
	{ category: "Superior",  type: "ranged", name: "Shuriken", range: { low: 0, high: 0 }
];